#%RAML 1.0 Trait
queryParameters:
  offset:
    description: list of returned results by this amount
    type: integer
    default: 0
    example: 0
    minimum: 0
  limit:
    description: number of items to be retrived in a single request
    type: integer
    default: 100
    example: 100
    minimum: 100
    